### PR TITLE
Show helpful error message when there are network problems

### LINKED ISSUE #306: Show a helpful error message when the server doesn't respond to AJAX calls
When the server is down or a network requests times out, the client assumes it was an evaluation error. We should detect the cases when evaluation fails due to network conditions and show an error message like the following:

> We couldn't evaluate the exercise, try again in a few minutes.

### PR DESCRIPTION
**Pull request by dialelo**
Closes #306 

@raulraja take a look please.

### CODE REVIEW

File: site/client/src/main/scala/Api.scala [hunk 1]
```diff
@@ -48,6 +48,17 @@ object Client {
...
       else
         EvaluationResult(false, e.method, r.responseText)
-    }).recover({ case exc: AjaxException ⇒ EvaluationResult(false, e.method, exc.xhr.responseText) })
+    }).recover({
+      case exc: AjaxException ⇒ {
+        EvaluationResult(
+          false,
+          e.method,
+          if (exc.isTimeout)
+            "We couldn't evaluate the exercise, please try again in a few minutes."
```
Comment (raulraja) [inline site/client/src/main/scala/Api.scala]: `We couldn't evaluate your exercise. You may be experience internet connectivity issues`

**Comment by raulraja** [comment]
LGTM
